name: Build MacCatalyst

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workloads
        run: dotnet workload install maui-android maui-ios maui-maccatalyst maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MacCatalyst .app
        run: dotnet build -f net8.0-maccatalyst -c Release

      - name: Zip .app bundle
        run: |
          cd bin/Release/net8.0-maccatalyst/maccatalyst-arm64
          zip -r YourApp.zip YourApp.app

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: bin/Release/net8.0-maccatalyst/maccatalyst-arm64/YourApp.zip

