name: Build MacCatalyst

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI Workloads
        run: dotnet workload install maui-android maui-ios maui-maccatalyst maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for MacCatalyst
        run: dotnet publish -f net9.0-maccatalyst -c Release -o ./output
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacApp
          path: ./output
